services:
  status:
    build: .
    container_name: status-service
    restart: unless-stopped
    user: "1001:1001" # required to set correct permissions
    ports:
      - "3909:3000"           # public - expose status page
      - "127.0.0.1:4909:3001" # admin - admin only, keep it local
    environment:
      - NODE_ENV=production  # change to development for testing or serve over https behind reverse proxy
      - TZ=Europe/London  # <--- Set your timezone here
      # Use the .env file to set these variables!
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./data:/app/data

  # reverse proxy example
  caddy:
    image: caddy:alpine
    container_name: status-caddy
    restart: unless-stopped
    ports:
      - "80:80"   # HTTP (Auto-redirects to HTTPS)
      - "443:443" # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    depends_on:
      - status
